AWSTemplateFormatVersion: '2010-09-09'
Description: 'Missing tables for Vehicle Guesser'

Resources:
  # Challenge Table
  ChallengeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: vehicle-guesser-challenges-prod
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: challengeId
          AttributeType: S
      KeySchema:
        - AttributeName: challengeId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # WebSocket Connections Table
  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: vehicle-guesser-connections-prod
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true