AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple Cognito User Pool for Vehicle Guesser'

Parameters:
  Environment:
    Type: String
    Default: prod
  EnableGoogleAuth:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: Enable Google OAuth authentication
  GoogleClientId:
    Type: String
    Default: ''
    Description: Google OAuth Client ID
  GoogleClientSecret:
    Type: String
    Default: ''
    NoEcho: true
    Description: Google OAuth Client Secret

Conditions:
  HasGoogleAuth: !And
    - !Equals [!Ref EnableGoogleAuth, 'true']
    - !Not [!Equals [!Ref GoogleClientId, '']]

Resources:
  # Lambda function for account linking
  AccountLinkingFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'vehicle-guesser-account-linking-${Environment}'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt AccountLinkingRole.Arn
      Code:
        ZipFile: |
          const { CognitoIdentityProviderClient, AdminGetUserCommand } = require('@aws-sdk/client-cognito-identity-provider');
          
          const cognitoClient = new CognitoIdentityProviderClient({ region: process.env.AWS_REGION });
          
          exports.handler = async (event) => {
              console.log('Pre-signup trigger event:', JSON.stringify(event, null, 2));
              
              try {
                  const { userPoolId, triggerSource, request } = event;
                  const { userAttributes } = request;
                  const email = userAttributes.email;
                  
                  // Only handle external provider signups
                  if (triggerSource === 'PreSignUp_ExternalProvider') {
                      console.log('External provider signup detected for email:', email);
                      
                      try {
                          // Check if user already exists with this email
                          await cognitoClient.send(new AdminGetUserCommand({
                              UserPoolId: userPoolId,
                              Username: email
                          }));
                          
                          console.log('Found existing user with email:', email);
                          
                          // Prevent creating duplicate user
                          throw new Error('An account with this email already exists. Please sign in with your email and password instead.');
                          
                      } catch (getUserError) {
                          if (getUserError.name === 'UserNotFoundException') {
                              console.log('No existing user found, allowing signup');
                              // Allow normal signup process
                          } else {
                              console.error('Error during account check:', getUserError);
                              throw getUserError;
                          }
                      }
                  }
                  
                  return event;
                  
              } catch (error) {
                  console.error('Pre-signup trigger error:', error);
                  throw error;
              }
          };
      Timeout: 30

  # IAM Role for Lambda
  AccountLinkingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: CognitoAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:AdminGetUser
                  - cognito-idp:AdminLinkProviderForUser
                Resource: !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/*'

  # Lambda permission for Cognito
  CognitoLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AccountLinkingFunction
      Action: lambda:InvokeFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/*'

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 'vehicle-guesser-${Environment}'
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      AliasAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireUppercase: false
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: name
          AttributeDataType: String
          Required: false
          Mutable: true
        - Name: picture
          AttributeDataType: String
          Required: false
          Mutable: true
      LambdaConfig:
        PreSignUp: !GetAtt AccountLinkingFunction.Arn

  # Google Identity Provider (conditional)
  GoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Condition: HasGoogleAuth
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: Google
      ProviderType: Google
      ProviderDetails:
        client_id: !Ref GoogleClientId
        client_secret: !Ref GoogleClientSecret
        authorize_scopes: 'email openid profile'
      AttributeMapping:
        email: email
        name: name
        picture: picture
        preferred_username: email
        username: sub

  # User Pool Domain for Hosted UI
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    DependsOn:
      - UserPool
    Properties:
      Domain: !Sub 'vehicle-guesser-${Environment}-${AWS::AccountId}'
      UserPoolId: !Ref UserPool

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn:
      - UserPool
    Properties:
      ClientName: !Sub 'vehicle-guesser-client-${Environment}'
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders: !If
        - HasGoogleAuth
        - [COGNITO, Google]
        - [COGNITO]
      CallbackURLs:
        - 'https://dw78cwmd7ajty.cloudfront.net'
        - 'http://localhost:5173'
        - 'http://localhost:5174'
      LogoutURLs:
        - 'https://dw78cwmd7ajty.cloudfront.net'
        - 'http://localhost:5173'
        - 'http://localhost:5174'
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AccessTokenValidity: 24
      IdTokenValidity: 24
      RefreshTokenValidity: 30

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'
  
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'
  
  UserPoolDomain:
    Description: Cognito Hosted UI Domain
    Value: !Sub 'https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com'
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolDomain'