AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple Cognito User Pool for Vehicle Guesser'

Parameters:
  Environment:
    Type: String
    Default: prod
  AppId:
    Type: String
    Default: 'com.yourcompany.vehicleguesser'
    Description: Mobile app bundle identifier
  EnableGoogleAuth:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: Enable Google OAuth authentication
  GoogleOAuthSecretName:
    Type: String
    Default: 'vehicle-guesser-google-oauth-prod-jR3mey'
    Description: Name of secret containing Google OAuth credentials
  GameDataTableName:
    Type: String
    Default: ''
    Description: Game data table name from backend stack

Conditions:
  HasGoogleAuth: !Equals [!Ref EnableGoogleAuth, 'true']
  NoGoogleAuth: !Not [!Equals [!Ref EnableGoogleAuth, 'true']]

Resources:
  # DynamoDB table for user account linking
  UserLinkingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'vehicle-guesser-user-linking-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # DynamoDB table for username uniqueness
  UsernameTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'vehicle-guesser-usernames-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH

  # Lambda function for account linking
  AccountLinkingFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'vehicle-guesser-account-linking-${Environment}'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt AccountLinkingRole.Arn
      Code:
        ZipFile: |
          const { DynamoDBClient } = require('@aws-sdk/client-dynamodb');
          const { DynamoDBDocumentClient, ScanCommand } = require('@aws-sdk/lib-dynamodb');
          
          const client = new DynamoDBClient({ region: 'eu-west-1' });
          const dynamodb = DynamoDBDocumentClient.from(client);
          
          exports.handler = async (event) => {
              console.log('Pre-signup trigger event:', JSON.stringify(event, null, 2));
              
              const { triggerSource, request } = event;
              const { userAttributes } = request;
              const email = userAttributes.email;
              const username = userAttributes.preferred_username;
              
              try {
                  if (!email) {
                      throw new Error('Email is required');
                  }
                  
                  // Check if email already exists in game data table
                  try {
                      const existingUsers = await dynamodb.send(new ScanCommand({
                          TableName: process.env.GAME_DATA_TABLE,
                          FilterExpression: '#profile.#email = :email',
                          ExpressionAttributeNames: {
                              '#profile': 'profile',
                              '#email': 'email'
                          },
                          ExpressionAttributeValues: {
                              ':email': email.toLowerCase()
                          }
                      }));
                      
                      if (existingUsers.Items && existingUsers.Items.length > 0) {
                          const existingUser = existingUsers.Items[0];
                          const existingAuthMethod = existingUser.profile?.authMethod;
                          const isGoogleSignup = triggerSource === 'PreSignUp_ExternalProvider';
                          const currentAuthMethod = isGoogleSignup ? 'google' : 'email';
                          
                          if (existingAuthMethod && existingAuthMethod !== currentAuthMethod) {
                              const errorMsg = existingAuthMethod === 'google' 
                                  ? 'This email is already registered with Google. Please use Google Sign-In.'
                                  : 'This email is already registered with email/password. Please use regular login.';
                              throw new Error(errorMsg);
                          }
                      }
                  } catch (scanError) {
                      // If the error is about conflicting auth methods, throw it to prevent signup
                      if (scanError.message.includes('already registered with')) {
                          console.error('Email conflict detected:', scanError.message);
                          throw scanError;
                      }
                      console.warn('Could not check existing users:', scanError.message);
                      // Continue with signup if scan fails for other reasons
                  }
                  
                  // For regular signup, require username
                  if (triggerSource === 'PreSignUp_SignUp') {
                      if (!username) {
                          throw new Error('Username is required');
                      }
                      
                      // Validate username format
                      if (username.length < 3 || username.length > 20) {
                          throw new Error('Username must be 3-20 characters');
                      }
                      
                      if (!/^[a-zA-Z0-9_]+$/.test(username)) {
                          throw new Error('Username can only contain letters, numbers, and underscores');
                      }
                  }
                  
                  console.log('Signup validation passed for:', email, 'via', triggerSource);
                  return event;
              } catch (error) {
                  console.error('Pre-signup validation error:', error);
                  throw error;
              }
          };
      Environment:
        Variables:
          GAME_DATA_TABLE: !Sub 'vehicle-guesser-gamedata-${Environment}'
      Timeout: 30


  # IAM Role for Lambda
  AccountLinkingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: BasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/vehicle-guesser-gamedata-${Environment}'
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GoogleOAuthSecretName}*'


  # Lambda permission for Cognito
  CognitoLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AccountLinkingFunction
      Action: lambda:InvokeFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/*'

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 'vehicle-guesser-${Environment}'
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireUppercase: false
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: name
          AttributeDataType: String
          Required: false
          Mutable: true
        - Name: picture
          AttributeDataType: String
          Required: false
          Mutable: true
        - Name: preferred_username
          AttributeDataType: String
          Required: false
          Mutable: true
      LambdaConfig:
        PreSignUp: !GetAtt AccountLinkingFunction.Arn

  # Google Identity Provider (conditional)
  GoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Condition: HasGoogleAuth
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: Google
      ProviderType: Google
      ProviderDetails:
        client_id: !Sub '{{resolve:secretsmanager:${GoogleOAuthSecretName}:SecretString:client_id}}'
        client_secret: !Sub '{{resolve:secretsmanager:${GoogleOAuthSecretName}:SecretString:client_secret}}'
        authorize_scopes: 'email openid profile'
      AttributeMapping:
        email: email
        name: name
        picture: picture
        preferred_username: preferred_username
        username: sub

  # User Pool Domain for Hosted UI
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    DependsOn:
      - UserPool
    Properties:
      Domain: !Sub 'vehicle-guesser-${Environment}-${AWS::AccountId}'
      UserPoolId: !Ref UserPool

  UserPoolClientWithGoogle:
    Type: AWS::Cognito::UserPoolClient
    Condition: HasGoogleAuth
    DependsOn:
      - UserPool
      - GoogleIdentityProvider
    Properties:
      ClientName: !Sub 'vehicle-guesser-client-${Environment}'
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO
        - Google
      CallbackURLs:
        - 'https://dw78cwmd7ajty.cloudfront.net'
        - 'http://localhost:5173'
        - 'http://localhost:5174'
        - !Sub '${AppId}://'
      LogoutURLs:
        - 'https://dw78cwmd7ajty.cloudfront.net'
        - 'http://localhost:5173'
        - 'http://localhost:5174'
        - !Sub '${AppId}://'
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AccessTokenValidity: 24
      IdTokenValidity: 24
      RefreshTokenValidity: 30

  UserPoolClientWithoutGoogle:
    Type: AWS::Cognito::UserPoolClient
    Condition: NoGoogleAuth
    DependsOn:
      - UserPool
    Properties:
      ClientName: !Sub 'vehicle-guesser-client-${Environment}'
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - 'https://dw78cwmd7ajty.cloudfront.net'
        - 'http://localhost:5173'
        - 'http://localhost:5174'
        - !Sub '${AppId}://'
      LogoutURLs:
        - 'https://dw78cwmd7ajty.cloudfront.net'
        - 'http://localhost:5173'
        - 'http://localhost:5174'
        - !Sub '${AppId}://'
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AccessTokenValidity: 24
      IdTokenValidity: 24
      RefreshTokenValidity: 30

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'
  
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !If
      - HasGoogleAuth
      - !Ref UserPoolClientWithGoogle
      - !Ref UserPoolClientWithoutGoogle
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'
  
  UserPoolDomain:
    Description: Cognito Hosted UI Domain
    Value: !Sub 'https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com'
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolDomain'