AWSTemplateFormatVersion: '2010-09-09'
Description: 'Secure Cognito configuration with Secrets Manager'

Parameters:
  Environment:
    Type: String
    Default: prod
  GoogleClientIdSecretArn:
    Type: String
    Description: ARN of secret containing Google OAuth Client ID
  GoogleClientSecretArn:
    Type: String
    Description: ARN of secret containing Google OAuth Client Secret

Resources:
  # Lambda to retrieve secrets
  SecretsRetrievalFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'cognito-secrets-retrieval-${Environment}'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt SecretsRetrievalRole.Arn
      Code:
        ZipFile: |
          const { SecretsManagerClient, GetSecretValueCommand } = require('@aws-sdk/client-secrets-manager');
          const client = new SecretsManagerClient();
          
          exports.handler = async (event) => {
            try {
              const { SecretId } = event.ResourceProperties;
              const response = await client.send(new GetSecretValueCommand({ SecretId }));
              return {
                PhysicalResourceId: SecretId,
                Data: { SecretValue: response.SecretString }
              };
            } catch (error) {
              throw new Error(`Failed to retrieve secret: ${error.message}`);
            }
          };

  SecretsRetrievalRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SecretsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: 
                  - !Ref GoogleClientIdSecretArn
                  - !Ref GoogleClientSecretArn

  # Custom resources to retrieve secrets
  GoogleClientIdSecret:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt SecretsRetrievalFunction.Arn
      SecretId: !Ref GoogleClientIdSecretArn

  GoogleClientSecretSecret:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt SecretsRetrievalFunction.Arn
      SecretId: !Ref GoogleClientSecretArn

Outputs:
  GoogleClientId:
    Description: Google OAuth Client ID (from Secrets Manager)
    Value: !GetAtt GoogleClientIdSecret.SecretValue
    
  GoogleClientSecret:
    Description: Google OAuth Client Secret (from Secrets Manager)
    Value: !GetAtt GoogleClientSecretSecret.SecretValue