AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple Cognito User Pool for Vehicle Guesser'

Parameters:
  Environment:
    Type: String
    Default: prod
  EnableGoogleAuth:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: Enable Google OAuth authentication

Conditions:
  HasGoogleAuth: !Equals [!Ref EnableGoogleAuth, 'true']

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 'vehicle-guesser-${Environment}'
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireUppercase: false
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: name
          AttributeDataType: String
          Required: false
          Mutable: true
        - Name: picture
          AttributeDataType: String
          Required: false
          Mutable: true

  # Google Identity Provider (conditional)
  GoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Condition: HasGoogleAuth
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: Google
      ProviderType: Google
      ProviderDetails:
        client_id: '{{resolve:ssm:/vehicle-guesser/google/client-id}}'
        client_secret: '{{resolve:ssm:/vehicle-guesser/google/client-secret}}' 
        authorize_scopes: 'email openid profile'
      AttributeMapping:
        email: email
        name: name
        picture: picture
        preferred_username: email

  # User Pool Domain for Hosted UI
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub 'vehicle-guesser-${Environment}-${AWS::AccountId}'
      UserPoolId: !Ref UserPool

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub 'vehicle-guesser-client-${Environment}'
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO_USER_POOLS
        - !If [HasGoogleAuth, Google, !Ref 'AWS::NoValue']
      CallbackURLs:
        - 'https://dw78cwmd7ajty.cloudfront.net'
        - 'http://localhost:5173'
      LogoutURLs:
        - 'https://dw78cwmd7ajty.cloudfront.net'
        - 'http://localhost:5173'
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AccessTokenValidity: 24
      IdTokenValidity: 24
      RefreshTokenValidity: 30

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'
  
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'
  
  UserPoolDomain:
    Description: Cognito Hosted UI Domain
    Value: !Sub 'https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com'
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolDomain'