AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB tables for rival challenge system'

Resources:
  MatchmakingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-matchmaking'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: skillLevel
          AttributeType: N
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: SkillLevelIndex
          KeySchema:
            - AttributeName: skillLevel
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Project
          Value: VehicleGuesser
        - Key: Environment
          Value: Production



Outputs:
  MatchmakingTableName:
    Description: 'Matchmaking table name'
    Value: !Ref MatchmakingTable
    Export:
      Name: !Sub '${AWS::StackName}-MatchmakingTable'

